<?php
/**
 * @file
 * Hook implementations for the age_checker module.
 */

define('AGE_CHECKER_VISIBILITY_NOTLISTED', 0);
define('AGE_CHECKER_VISIBILITY_LISTED', 1);

/**
 * Implements hook_menu().
 */
function age_checker_menu() {
  $items['admin/config/people/age_checker'] = array(
    'title'            => 'Age Checker Settings',
    'description'      => 'Configure default behaviour of Age Checker Settings.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('age_checker_admin_form'),
    'access callback'  => 'user_access',
    'access arguments' => array('administer age checker settings'),
    'file'             => 'age_checker.admin.inc',
  );

  $items['admin/config/people/age_checker_mapping'] = array(
    'title'            => 'Age Checker Mapping',
    'description'      => 'Language to country mapping will take place.',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('age_checker_mapping_admin_form'),
    'access callback'  => 'user_access',
    'access arguments' => array('administer age checker settings'),
    'file'             => 'age_checker.admin.inc',
  );
  return $items;
}
